In [96]:
import pandas as pd

In [97]:
df=pd.read_csv('sales_data_sample.csv',encoding='ISO-8859-1')

In [98]:
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [99]:
df.tail(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
91,10237,39,100.0,9,7023.90,4/5/2004 0:00,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Large
92,10251,43,100.0,4,7078.23,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Large
93,10263,41,100.0,4,8336.94,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,NaN,Bridgewater,CT,97562,USA,NaN,King,Julie,Large
94,10275,36,100.0,3,6901.92,7/23/2004 0:00,Shipped,3,7,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
95,10285,27,100.0,8,5438.07,8/27/2004 0:00,Shipped,3,8,2004,...,39323 Spinnaker Dr.,NaN,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium

In [100]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.00000,96.000000,96.000000
mean,10247.937500,35.583333,96.471979,5.395833,5274.936875,2.739583,7.09375,2003.750000,152.270833
std,90.331764,9.406232,11.137722,3.851122,2358.161503,1.171996,3.57205,0.680557,51.201455
min,10103.000000,20.000000,34.910000,1.000000,733.110000,1.000000,1.00000,2003.000000,95.000000
25%,10172.500000,27.000000,100.000000,2.000000,3615.630000,2.000000,4.00000,2003.000000,95.000000
50%,10241.000000,36.500000,100.000000,4.000000,4961.110000,3.000000,7.00000,2004.000000,118.000000
75%,10318.000000,42.000000,100.000000,8.000000,7023.920000,4.000000,11.00000,2004.000000,214.000000
max,10424.000000,66.000000,100.000000,17.000000,12001.000000,4.000000,12.00000,2005.000000,214.000000

In [101]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [102]:
## Handling missing values
df.isnull()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
92,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
93,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
94,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False

In [103]:
df.isnull().any(axis=1)   ## [False, True] → True
                          ## ## axis: 1 means  "Does this row have at least one missing value?"

0     True
1     True
2     True
3     True
4     True
      ...
91    True
92    True
93    True
94    True
95    True
Length: 96, dtype: bool

In [104]:
df.isnull().any()   ## axis: 0 means  "Does this column have at least one missing value?"

ORDERNUMBER         False
QUANTITYORDERED     False
PRICEEACH           False
ORDERLINENUMBER     False
SALES               False
ORDERDATE           False
STATUS              False
QTR_ID              False
MONTH_ID            False
YEAR_ID             False
PRODUCTLINE         False
MSRP                False
PRODUCTCODE         False
CUSTOMERNAME        False
PHONE               False
ADDRESSLINE1        False
ADDRESSLINE2         True
CITY                False
STATE                True
POSTALCODE           True
COUNTRY             False
TERRITORY            True
CONTACTLASTNAME     False
CONTACTFIRSTNAME    False
DEALSIZE            False
dtype: bool

In [105]:
df.isnull().sum()      ## it shows how many missing values there are in each column

ORDERNUMBER          0
QUANTITYORDERED      0
PRICEEACH            0
ORDERLINENUMBER      0
SALES                0
ORDERDATE            0
STATUS               0
QTR_ID               0
MONTH_ID             0
YEAR_ID              0
PRODUCTLINE          0
MSRP                 0
PRODUCTCODE          0
CUSTOMERNAME         0
PHONE                0
ADDRESSLINE1         0
ADDRESSLINE2        83
CITY                 0
STATE               32
POSTALCODE           8
COUNTRY              0
TERRITORY           48
CONTACTLASTNAME      0
CONTACTFIRSTNAME     0
DEALSIZE             0
dtype: int64

In [106]:
df.fillna(0)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,0,NYC,NY,10022,USA,0,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,0,Reims,0,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,0,Paris,0,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,0,Pasadena,CA,90003,USA,0,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,0,San Francisco,CA,0,USA,0,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,10237,39,100.00,9,7023.90,4/5/2004 0:00,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,0,Frick,Michael,Large
92,10251,43,100.00,4,7078.23,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,0,Newark,NJ,94019,USA,0,Brown,William,Large
93,10263,41,100.00,4,8336.94,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,0,Bridgewater,CT,97562,USA,0,King,Julie,Large
94,10275,36,100.00,3,6901.92,7/23/2004 0:00,Shipped,3,7,2004,...,"67, rue des Cinquante Otages",0,Nantes,0,44000,France,EMEA,Labrune,Janine,Medium
95,10285,27,100.00,8,5438.07,8/27/2004 0:00,Shipped,3,8,2004,...,39323 Spinnaker Dr.,0,Cambridge,MA,51247,USA,0,Hernandez,Marta,Medium

In [107]:
df['STATE_FillNA']=df['STATE'].fillna(df['STATE'].mean()) ## here it is right but in dataset the STATE has no int/floating point value..here is string so it cant find the mean of that.

## It will create a new column named 'STATE_FillNA' and in this column you will get the mean

TypeError: can only concatenate str (not "int") to str

In [ ]:
## Renaming Column

df=df.rename(columns={'SALEs STATUS':'SALES STATUS'})

In [ ]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,SALES STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
#3 change datatype

df.dtypes

df['PRICEEACH_new']=df['PRICEEACH'].astype(int)
df.head()

## if there is an empty field then we should do
## df['PRICEEACH_new']=df['PRICEEACH'].fillna(df['PRICEEACH'].mean()).astype(int)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,SALES STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,PRICEEACH_new
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,95
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,81
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,94
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,83
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,100

In [ ]:
## PRICEEACH Columns value will be double

df['PRICEEACH_double']=df['PRICEEACH'].apply(lambda x:x**2)
df.head(20)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,PRICEEACH_double
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,9158.4900
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,6617.8225
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,8975.6676
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,6932.2276
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,10000.0000
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium,9343.1556
6,10180,29,86.13,9,2497.77,11/11/2003 0:00,Shipped,4,11,2003,...,NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small,7418.3769
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium,10000.0000
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small,9716.0449
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium,10000.0000
10,10223,37,100.00,1,3965.66,2/20/2004 0:00,Shipped,1,2,2004,...,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium,10000.0000
11,10237,23,100.00,7,2333.12,4/5/2004 0:00,Shipped,2,4,2004,...,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small,10000.0000
12,10251,28,100.00,2,3188.64,5/18/2004 0:00,Shipped,2,5,2004,...,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Medium,10000.0000
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,NaN,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium,10000.0000
14,10275,45,92.83,1,4177.35,7/23/2004 0:00,Shipped,3,7,2004,...,NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium,8617.4089
15,10285,36,100.00,6,4099.68,8/27/2004 0:00,Shipped,3,8,2004,...,NaN,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium,10000.0000
16,10299,23,100.00,9,2597.39,9/30/2004 0:00,Shipped,3,9,2004,...,NaN,Helsinki,NaN,21240,Finland,EMEA,Karttunen,Matti,Small,10000.0000
17,10309,41,100.00,5,4394.38,10/15/2004 0:00,Shipped,4,10,2004,...,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium,10000.0000
18,10318,46,94.74,1,4358.04,11/2/2004 0:00,Shipped,4,11,2004,...,NaN,Allentown,PA,70267,USA,NaN,Yu,Kyung,Medium,8975.6676
19,10329,42,100.00,1,4396.14,11/15/2004 0:00,Shipped,4,11,2004,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium,10000.0000

In [ ]:
## Data Aggregating and Grouping

grouped_mean=df.groupby('CONTACTLASTNAME')['SALES'].mean()
grouped_mean.head()

CONTACTLASTNAME
Accorti     3619.894615
Ashworth    3094.270784
Barajas     3813.197333
Benitez     3804.758846
Bennett     3009.263077
Name: SALES, dtype: float64

In [ ]:
grouped_mean2=df.groupby(['CONTACTFIRSTNAME','CONTACTLASTNAME'])['SALES'].mean()
print(grouped_mean2)

CONTACTFIRSTNAME  CONTACTLASTNAME
Adrian            Huxley             3295.021304
Akiko             Shimamura          3767.585625
Allen             Nelson             3399.082500
Ann               Brown              3415.557692
Anna              O'Hara             3347.741957
                                        ...
Violeta           Benitez            3804.758846
Wendy             Victorino          3208.298056
William           Brown              3963.247143
Wing C            Tam                3112.889429
Yoshi             Tannamuri          3419.950909
Name: SALES, Length: 92, dtype: float64

In [ ]:
grouped_sum=df.groupby(['MONTH_ID','CONTACTFIRSTNAME'])['SALES'].sum()
print(grouped_sum.head(12))

MONTH_ID  CONTACTFIRSTNAME
1         Akiko                38191.39
          Allen                31474.78
          Anna                 29852.17
          Diego               109787.13
          Dominique            51172.65
          Jonas                54702.00
          Julie                44273.36
          Juri                 13529.57
          Kalle                51373.49
          Laurence              2317.44
          Mart¡n               24995.47
          Mary                 54536.87
Name: SALES, dtype: float64

In [ ]:
grouped_mean3=df.groupby(['MONTH_ID','CONTACTFIRSTNAME'])['SALES'].mean()
print(grouped_mean3)

MONTH_ID  CONTACTFIRSTNAME
1         Akiko               4243.487778
          Allen               3934.347500
          Anna                3316.907778
          Diego               3785.763103
          Dominique           3411.510000
                                 ...
12        Leslie              2882.132500
          Paul                3776.802500
          Steve               2744.853333
          Valarie             4072.418846
          Yoshi               3514.746364
Name: SALES, Length: 252, dtype: float64

In [ ]:
## Aggregate multiple functions

grouped_agg=df.groupby('CONTACTFIRSTNAME')['SALES'].agg(['sum','mean','count'])  ## count: The number of orders/rows in the dataset for that contact’s first name.
print(grouped_agg)

                       sum       mean  count
CONTACTFIRSTNAME
Adrian             1451.00  1451.0000      1
Christina          7209.11  7209.1100      1
Daniel             3884.34  3884.3400      1
Diego              7516.08  7516.0800      1
Dominique          4708.44  4708.4400      1
Elizabeth          2434.56  2434.5600      1
Georg              7737.93  7737.9300      1
Janine             4910.46  2455.2300      2
Jonas              9799.00  4899.5000      2
Julie             14797.27  3699.3175      4
Juri               3479.76  3479.7600      1
Kwai               7267.14  3633.5700      2
Kyung              4358.04  4358.0400      1
Marta              4099.68  4099.6800      1
Martine            2497.77  2497.7700      1
Martï¿½n           7329.06  7329.0600      1
Matti              2597.39  2597.3900      1
Michael            2333.12  2333.1200      1
Paul               2765.90  2765.9000      1
Peter              3965.66  3965.6600      1
Veysel             5512.32  5512.3200      1
Violeta            3207.12  3207.1200      1
William            3188.64  3188.6400      1

In [ ]:
## Merging and Joining DataFrames

# Create simple DataFrames
df1=pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'],'Value2':[3,4,5]})

  key  Value1
0   A       1
1   B       2
2   C       3

In [ ]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [110]:
df2

  key  Value2
0   A       3
1   B       4
2   D       5

In [ ]:
## Merge DataFrames on the 'Key Columns'

pd.merge(df1,df2,on='key',how='inner')  ## inner means it take only common names key

  key  Value1  Value2
0   A       1       3
1   B       2       4

In [ ]:
pd.merge(df1,df2,on='key',how='outer') ## it will take all the keys but which value is not present at that place it is NAN

  key  Value1  Value2
0   A     1.0     3.0
1   B     2.0     4.0
2   C     3.0     NaN
3   D     NaN     5.0

In [113]:
pd.merge(df1,df2,on='key',how='left')

  key  Value1  Value2
0   A       1     3.0
1   B       2     4.0
2   C       3     NaN

In [114]:
pd.merge(df1,df2,on='key',how='right')

  key  Value1  Value2
0   A     1.0       3
1   B     2.0       4
2   D     NaN       5