In [38]:
import pandas as pd
from io import StringIO

# The outer [ ... ] → makes it an array (so Pandas sees it as tabular).
Data = """
[
{
  "employee_id": 101,
  "first_name": "Alice",
  "last_name": "Johnson",
  "email": "alice.johnson@example.com",
  "phone": "+1-202-555-0147",
  "job_title": "Software Engineer",
  "department": "IT",
  "hire_date": "2021-06-15",
  "salary": 75000,
  "address": {
    "street": "123 Maple Street",
    "city": "San Francisco",
    "state": "CA",
    "zip": "94105",
    "country": "USA"
  },
  "skills": ["Python", "SQL", "Machine Learning"],
  "manager_id": 56
}]"""

df=pd.read_json(StringIO(Data))

In [39]:
df

,employee_id,first_name,last_name,email,phone,job_title,department,hire_date,salary,address,skills,manager_id
0,101,Alice,Johnson,alice.johnson@example.com,+1-202-555-0147,Software Engineer,IT,2021-06-15,75000,"{'street': '123 Maple Street', 'city': 'San Fr...","[Python, SQL, Machine Learning]",56

In [40]:
df.to_json()

'{"employee_id":{"0":101},"first_name":{"0":"Alice"},"last_name":{"0":"Johnson"},"email":{"0":"alice.johnson@example.com"},"phone":{"0":"+1-202-555-0147"},"job_title":{"0":"Software Engineer"},"department":{"0":"IT"},"hire_date":{"0":"2021-06-15"},"salary":{"0":75000},"address":{"0":{"street":"123 Maple Street","city":"San Francisco","state":"CA","zip":"94105","country":"USA"}},"skills":{"0":["Python","SQL","Machine Learning"]},"manager_id":{"0":56}}'

In [41]:
df.to_json(orient="index")

'{"0":{"employee_id":101,"first_name":"Alice","last_name":"Johnson","email":"alice.johnson@example.com","phone":"+1-202-555-0147","job_title":"Software Engineer","department":"IT","hire_date":"2021-06-15","salary":75000,"address":{"street":"123 Maple Street","city":"San Francisco","state":"CA","zip":"94105","country":"USA"},"skills":["Python","SQL","Machine Learning"],"manager_id":56}}'

In [42]:
df.to_json(orient="records")

'[{"employee_id":101,"first_name":"Alice","last_name":"Johnson","email":"alice.johnson@example.com","phone":"+1-202-555-0147","job_title":"Software Engineer","department":"IT","hire_date":"2021-06-15","salary":75000,"address":{"street":"123 Maple Street","city":"San Francisco","state":"CA","zip":"94105","country":"USA"},"skills":["Python","SQL","Machine Learning"],"manager_id":56}]'

In [43]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [44]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [45]:
df.to_csv("wine.csv")

In [46]:
df=pd.read_html("https://fdic.gov/bank-failures/failed-bank-list")

In [47]:
df

[                                            Bank Name                City  \
 0                        The Santa Anna National Bank          Santa Anna
 1                                Pulaski Savings Bank             Chicago
 2                  The First National Bank of Lindsay             Lindsay
 3               Republic First Bank dba Republic Bank        Philadelphia
 4                                       Citizens Bank            Sac City
 5                            Heartland Tri-State Bank             Elkhart
 6                                 First Republic Bank       San Francisco
 7                                      Signature Bank            New York
 8                                 Silicon Valley Bank         Santa Clara
 9                                   Almena State Bank              Almena
 10                         First City Bank of Florida   Fort Walton Beach
 11                               The First State Bank       Barboursville
 12                                 Ericson State Bank             Ericson
 13                   City National Bank of New Jersey              Newark
 14                                      Resolute Bank              Maumee
 15                              Louisa Community Bank              Louisa
 16                               The Enloe State Bank              Cooper
 17                Washington Federal Bank for Savings             Chicago
 18    The Farmers and Merchants State Bank of Argonia             Argonia
 19                                Fayette County Bank          Saint Elmo
 20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 21                                     First NBC Bank         New Orleans
 22                                      Proficio Bank  Cottonwood Heights
 23                      Seaway Bank and Trust Company             Chicago
 24                             Harvest Community Bank          Pennsville

             State   Cert                Acquiring Institution  \
 0           Texas   5520            Coleman County State Bank
 1        Illinois  28611                      Millennium Bank
 2        Oklahoma   4134               First Bank & Trust Co.
 3    Pennsylvania  27332    Fulton Bank, National Association
 4            Iowa   8758            Iowa Trust & Savings Bank
 5          Kansas  25851               Dream First Bank, N.A.
 6      California  59017            JPMorgan Chase Bank, N.A.
 7        New York  57053                  Flagstar Bank, N.A.
 8      California  24735  First Citizens Bank & Trust Company
 9          Kansas  15426                          Equity Bank
 10        Florida  16748            United Fidelity Bank, fsb
 11  West Virginia  14361                       MVB Bank, Inc.
 12       Nebraska  18265           Farmers and Merchants Bank
 13     New Jersey  21111                      Industrial Bank
 14           Ohio  58317                   Buckeye State Bank
 15       Kentucky  58112    Kentucky Farmers Bank Corporation
 16          Texas  10716                   Legend Bank, N. A.
 17       Illinois  30570                   Royal Savings Bank
 18         Kansas  17719                          Conway Bank
 19       Illinois   1802            United Fidelity Bank, fsb
 20      Wisconsin  30003  First-Citizens Bank & Trust Company
 21      Louisiana  58302                         Whitney Bank
 22           Utah  35495                    Cache Valley Bank
 23       Illinois  19328                  State Bank of Texas
 24     New Jersey  34951  First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       June 27, 2025                 10549
 1    January 17, 2025                 10548
 2    October 18, 2024                 10547
 3      April 26, 2024                 10546
 4    November 3, 2023                 10545
 5       July 28, 2023                 10544
 6         May 1, 2023                 10543
 7      March 12, 2023                 10540
 8      March 10, 2023                 10539
 9    October 23, 2020                 10538
 10   October 16, 2020                 10537
 11      April 3, 2020                 10536
 12  February 14, 2020                 10535
 13   November 1, 2019                 10534
 14   October 25, 2019                 10533
 15   October 25, 2019                 10532
 16       May 31, 2019                 10531
 17  December 15, 2017                 10530
 18   October 13, 2017                 10529
 19       May 26, 2017                 10528
 20        May 5, 2017                 10527
 21     April 28, 2017                 10526
 22      March 3, 2017                 10525
 23   January 27, 2017                 10524
 24   January 13, 2017                 10523  ]

In [48]:
df[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545

In [49]:
df=pd.read_html("https://fdic.gov/bank/individual/failed/banklist.html")

In [50]:
df

[                                            Bank Name                City  \
 0                        The Santa Anna National Bank          Santa Anna
 1                                Pulaski Savings Bank             Chicago
 2                  The First National Bank of Lindsay             Lindsay
 3               Republic First Bank dba Republic Bank        Philadelphia
 4                                       Citizens Bank            Sac City
 5                            Heartland Tri-State Bank             Elkhart
 6                                 First Republic Bank       San Francisco
 7                                      Signature Bank            New York
 8                                 Silicon Valley Bank         Santa Clara
 9                                   Almena State Bank              Almena
 10                         First City Bank of Florida   Fort Walton Beach
 11                               The First State Bank       Barboursville
 12                                 Ericson State Bank             Ericson
 13                   City National Bank of New Jersey              Newark
 14                                      Resolute Bank              Maumee
 15                              Louisa Community Bank              Louisa
 16                               The Enloe State Bank              Cooper
 17                Washington Federal Bank for Savings             Chicago
 18    The Farmers and Merchants State Bank of Argonia             Argonia
 19                                Fayette County Bank          Saint Elmo
 20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 21                                     First NBC Bank         New Orleans
 22                                      Proficio Bank  Cottonwood Heights
 23                      Seaway Bank and Trust Company             Chicago
 24                             Harvest Community Bank          Pennsville

             State   Cert                Acquiring Institution  \
 0           Texas   5520            Coleman County State Bank
 1        Illinois  28611                      Millennium Bank
 2        Oklahoma   4134               First Bank & Trust Co.
 3    Pennsylvania  27332    Fulton Bank, National Association
 4            Iowa   8758            Iowa Trust & Savings Bank
 5          Kansas  25851               Dream First Bank, N.A.
 6      California  59017            JPMorgan Chase Bank, N.A.
 7        New York  57053                  Flagstar Bank, N.A.
 8      California  24735  First Citizens Bank & Trust Company
 9          Kansas  15426                          Equity Bank
 10        Florida  16748            United Fidelity Bank, fsb
 11  West Virginia  14361                       MVB Bank, Inc.
 12       Nebraska  18265           Farmers and Merchants Bank
 13     New Jersey  21111                      Industrial Bank
 14           Ohio  58317                   Buckeye State Bank
 15       Kentucky  58112    Kentucky Farmers Bank Corporation
 16          Texas  10716                   Legend Bank, N. A.
 17       Illinois  30570                   Royal Savings Bank
 18         Kansas  17719                          Conway Bank
 19       Illinois   1802            United Fidelity Bank, fsb
 20      Wisconsin  30003  First-Citizens Bank & Trust Company
 21      Louisiana  58302                         Whitney Bank
 22           Utah  35495                    Cache Valley Bank
 23       Illinois  19328                  State Bank of Texas
 24     New Jersey  34951  First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       June 27, 2025                 10549
 1    January 17, 2025                 10548
 2    October 18, 2024                 10547
 3      April 26, 2024                 10546
 4    November 3, 2023                 10545
 5       July 28, 2023                 10544
 6         May 1, 2023                 10543
 7      March 12, 2023                 10540
 8      March 10, 2023                 10539
 9    October 23, 2020                 10538
 10   October 16, 2020                 10537
 11      April 3, 2020                 10536
 12  February 14, 2020                 10535
 13   November 1, 2019                 10534
 14   October 25, 2019                 10533
 15   October 25, 2019                 10532
 16       May 31, 2019                 10531
 17  December 15, 2017                 10530
 18   October 13, 2017                 10529
 19       May 26, 2017                 10528
 20        May 5, 2017                 10527
 21     April 28, 2017                 10526
 22      March 3, 2017                 10525
 23   January 27, 2017                 10524
 24   January 13, 2017                 10523  ]

In [ ]:
import requests
url="https://en.wikipedia.org/wiki/Mobile_country_code"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
pd.read_html(response.text,header=0)

C:\Users\User\AppData\Local\Temp\ipykernel_5552\1235339151.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(response.text,header=0)

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any
 1    1    1  TEST  Test network  Operational         any
 2  999   99   NaN  Internal use  Operational         any
 3  999  999   NaN  Internal use  Operational         any

                               References and notes
 0                                              NaN
 1                                              NaN
 2  Internal use in private networks, no roaming[6]
 3  Internal use in private networks, no roaming[6]  ,
      Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns],
      MCC  MNC     Brand                  Operator           Status  \
 0    901    1       NaN                   Webbing          Unknown
 1    901    2       NaN            GlobalmatiX AG          Unknown
 2    901    3   Iridium                       NaN      Operational
 3    901    4       NaN  BBIX Singapore Pte. Ltd.          Unknown
 4    901    5       NaN      Thuraya RMSS Network      Operational
 ..   ...  ...       ...                       ...              ...
 99   902    1       NaN        MulteFire Alliance      Operational
 100  991    1       NaN    World's Global Telecom  Not operational
 101  991    2  5G Croco               Orange S.A.  Not operational
 102  991    3       NaN                 Halys SAS  Not operational
 103  991    4       NaN              E-Space Inc.          Unknown

     Bands (MHz)                               References and notes
 0          MVNO            Former ICO Satellite Management[51][52]
 1       Unknown  Former Sense Communications International; veh...
 2     Satellite                                                NaN
 3       Unknown                              Former Globalstar[54]
 4     Satellite                                                NaN
 ..          ...                                                ...
 99          LTE                                           [6][127]
 100     Unknown  temporarily assigned until 15 January 2021[104...
 101          5G  temporarily assigned until 6 August 2022[129][...
 102     Unknown  temporary assignment for trial until 5 April 2...
 103   Satellite  temporary assignment for trial until 17 Oct 20...

 [104 rows x 7 columns],
    MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
 0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                 References and notes
 0  There appears to be no officially assigned MCC...  ,
                                vteTelecommunications  \
 0                                            History
 1                                           Pioneers
 2                                 Transmission media
 3                     Network topology and switching
 4                                       Multiplexing
 5                                           Concepts
 6                                   Types of network
 7                                   Notable networks
 8                                          Locations
 9  Telecommunication portal  Category  Outline  C...

                              vteTelecommunications.1
 0  Beacon Broadcasting Cable protection system Ca...
 1  Nasir Ahmed Edwin Howard Armstrong Mohamed M. ...
 2  Coaxial cable Fiber-optic communication optica...
 3  Bandwidth Links Network switching circuit pack...
 4  Space-division Frequency-division Time-divisio...
 5  Communication protocol Computer network Data t...
 6  Cellular network Ethernet ISDN LAN Mobile NGN ...
 7  ARPANET BITNET CYCLADES FidoNet Internet Inter...
 8  Africa Americas North South Antarctica Asia Eu...
 9  Telecommunication portal  Category  Outline  C...  ]

In [65]:
import requests
url="https://en.wikipedia.org/wiki/Mobile_country_code"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
pd.read_html(response.text,match="Country",header=0)[0]

C:\Users\User\AppData\Local\Temp\ipykernel_5552\777746436.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(response.text,match="Country",header=0)[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [ ]:
!pip install openpyxl

In [ ]:
df=pd.read_excel('data.xlsx')

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [69]:
df

     NAME  Age
0    Gazi   23
1  Tousif   43
2   Nuhan   21

In [ ]:
## pickle file
df.to_pickle('df2')

In [73]:
pd.read_pickle("df2")

     NAME  Age
0    Gazi   23
1  Tousif   43
2   Nuhan   21